spring:
  cloud:
    gateway:
      routes:
        - id: YelpService
          uri: https://api.yelp.com
          predicates:
             - Path=/v3/businesses/**,/v3/transactions/**
          filters:
            - IDLValidationFilter

