spring:
  cloud:
    gateway:
      routes:
        - id: YelpAPI
          uri: https://api.yelp.com
          predicates:
             - Path=/v3/businesses/**
        - id: AmadeusFlightAPI
          uri: https://test.api.amadeus.com
          predicates:
             - Path=/v2/shopping/**
        - id: AmadeusHotelAPI
          uri: https://test.api.amadeus.com
          predicates:
             - Path=/v3/shopping/**
        - id: GitHubAPI
          uri: https://api.github.com
          predicates:
             - Path=/orgs/**
        - id: MarvelAPI
          uri: https://gateway.marvel.com
          predicates:
             - Path=/v1/public/**
       # - id: OmdbAPIBySearch
       #   uri: https://omdbapi.com
       #   predicates:
       #      - Path=/**
       # - id: OmdbAPIByTitleOrID
       #   uri: https://omdbapi.com
       #   predicates:
       #      - Path=/**
        - id: SpotifyAPIAlbums
          uri: https://api.spotify.com
          predicates:
             - Path=/v1/albums/**
        - id: SpotifyAPIArtists
          uri: https://api.spotify.com
          predicates:
             - Path=/v1/artists/**
        - id: YoutubeAPI
          uri: https://youtube.googleapis.com/
          predicates:
             - Path=/youtube/**

